<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <UserSecretsId>99f62a0c-82a6-457d-bb6a-1aea76fecaf1</UserSecretsId>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.35" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
        <PackageReference Include="DeepL.net" Version="1.10.0" />
        <PackageReference Include="Google.Apis.Texttospeech.v1" Version="1.68.0.3568" />
        <PackageReference Include="Google.Cloud.TextToSpeech.V1" Version="3.8.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

</Project>
